---
repos:
  - repo: local
    hooks:
      - id: linter
        name: Linter
        pass_filenames: False
        language: system
        entry: npm run lint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: no-commit-to-branch
        name: Check if commit is not in branch 'master'
        args:
          - --branch=main # For future us
          - --branch=master

      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: mixed-line-ending
