name: Lint

on:
  push:
  pull_request:
    paths:
      - "**.js"
      - "**.jsx"
      - "**.ts"
      - "**.tsx"

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
